### ISSUE TITLE
我打开之后有报错 

### ISSUE THREAD

**Issue by shimmer0709** [Zhen-XIA/JumpJump#1]
Exception in thread Thread-1 (algoExec):
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\JumpJump-pyqt-V1\myUi.py", line 40, in algoExec
    img, drawImg = jumpCore.adbReadSouceImg()
  File "C:\Users\Administrator\Desktop\JumpJump-pyqt-V1\jumpCore.py", line 28, in adbReadSouceImg
    img = img[screenH:screenH+screenW,:]
TypeError: 'NoneType' object is not subscriptable

**Comment by MT-Zhen** [comment]
请检查一下python的版本，此外还有相关的库是否安装好。

**Comment by shimmer0709** [comment]
好的，等有空我回去试下，在加班呢
